version: '1.0'

stages:
- preparation
- test
- build
- push
- run

steps:

  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'

  install_dependencies:
    title: 'Installing testing dependencies'
    stage: preparation
    image: node:12.13.0
    commands:
    - yarn install --frozen-lockfile

  lint:
    title: 'lint code'
    stage: preparation
    image: node:12.13.0
    commands:
    - yarn lint


  build_step:
    title: "Building production image"
    stage: build
    type: build
    dockerfile: Dockerfile
    image_name: codefresh/cf-k8s-agent
    metadata:
      set:
      - CF_QUALITY: true
      
  build_rollback_action: 
    title: "Building rollback action image"
    stage: build
    type: build
    dockerfile: actions/rollback/Dockerfile
    image_name: codefresh/cf-k8s-agent-rollback
    metadata:
      set:
      - CF_QUALITY: true

  push_rollback_action_to_dockerhub:
      title: 'Pushing rollback image to dockerhub'
      stage: push
      type: push
      image_name: codefresh/cf-k8s-agent-rollback
      registry: dockerhub
      candidate: ${{build_rollback_action}}
      tags:
      - ${{CF_BRANCH_TAG_NORMALIZED}}
      - ${{CF_REVISION}}
      - latest
      when:
       branch:
        only:
         - master

  push_to_dockerhub:
    title: 'Pushing image to dockerhub'
    stage: push
    type: push
    image_name: ${{IMAGE_NAME}}
    registry: dockerhub
    candidate: ${{build_step}}
    tags:
    - ${{CF_BRANCH_TAG_NORMALIZED}}
    - ${{CF_REVISION}}
    - latest
    - stable
    when:
     branch:
      only:
       - master