apiVersion: v1
name: k8s-agent
version: 0.0.25
description: Kubernetes agent for monitoring resources
icon: 'https://pngimage.net/wp-content/uploads/2018/06/secret-agent-png-2.png'
keywords:
- kubernetes
- agent
