apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      {{- if .Values.redeploy }}
      annotations:
        forceRedeployUniqId: {{ now | quote }}
      {{- end }}
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Values.imageTag | quote }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
          - name: SERVICE_NAME
            value: {{ template "name" . }}
          - name: PORT
            value: {{ .Values.port | quote }}
          - name: CLUSTER_URL
            value: {{ .Values.CLUSTER_URL | quote }}
          - name: CLUSTER_TOKEN
            value: {{ .Values.CLUSTER_TOKEN | quote }}
          - name: CLUSTER_CA
            value: {{ .Values.CLUSTER_CA | quote }}
          - name: CF_API_TOKEN
            value: {{ .Values.CF_API_TOKEN | quote }}
          - name: CLUSTER_ID
            value: {{ .Values.CLUSTER_ID | quote }}
          - name: CF_API_URL
            value: {{ .Values.CF_API_URL | quote }}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/ping
            port: {{ .Values.port }}
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
