apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
        - name: {{ template "fullname" . }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          env:
            - name: CF_API_TOKEN
              value: {{ .Values.cfApiToken }}
            - name: CF_API_URL
              value: {{ .Values.cfApiUrl }}
            - name: CLUSTER_ID
              value: {{ .Values.clusterId }}
            - name: CLEAN
              value: "{{ .Values.clean }}"
            - name: ACCOUNTS
              value: '{{ .Values.ACCOUNTS }}'
          ports:
            - containerPort: {{ .Values.port }}
