apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-svc"
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ template "fullname" . }}
