# serviceType type of the service, set to LoadBalancer to expose the ip when there is not ingress
serviceType: ClusterIP

# replicaCount number of pods to be schedualed
replicaCount: 1

## imagePullPolicy 'Always' if imageTag is 'latest', else set to 'IfNotPresent' ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: Always

# redeploy whenever to force redeploy
redeploy: false

# imageTag set the tag of the image
imageTag: master

# image base name of the image
image:  r.cfcr.io/codefresh-inc/codefresh/cf-k8s-agent

# env set of evnrionment varialbe to be add to the containers
#env:

# CLUSTER_URL - optional. for setup outside cluster when current context is used
# CLUSTER_TOKEN - optional. for setup outside cluster when current context is used
# CLUSTER_CA - optional. for setup outside cluster when current context is used
# CF_API_TOKEN - should be set when the chart is installing
# CLUSTER_ID - cluster name as it registered in account
CF_API_URL: https://q.codefresh.io/api/k8s-monitor

# port container port
port: 80

# servicePort port of the kubernetes service listen to
servicePort: 80
